### ISSUE TITLE
dev mode

### ISSUE THREAD

**Issue by mikeparadinas** [DJScias/Discord-Datamining#5]
http://image.prntscr.com/image/a7b5b29dea874d29bb74b578da44ba2c.jpeg
http://image.prntscr.com/image/5ab63b372d994bc4a3ed839d3f4b3741.jpeg
how do I get into this dev mode

**Comment by IanMurray** [comment]
This isn't appropriate for GitHub issues. Requesting close & lock.

**Comment by DJScias** [comment]
We do not endorse any sort of modifications to the client (plus it's against Discord's ToS). There is no 'legit' way to receive dev mode.

Closed.
